/*
 * nano_imu_ble_sender.ino
 * --------------------------------------------------------------------------
 * Arduino Nano 33 BLE original generation + LSM9DS1 IMU
 *
 * Role:
 *   Nano 33 BLE = BLE Peripheral / Sensor Node
 *
 * It reads accelerometer + gyroscope, computes lightweight features,
 * classifies simple cane movement phase, and sends CSV payload over BLE.
 *
 * Payload:
 *   IMU,timestamp_ms,ax_ms2,ay_ms2,az_ms2,gx_dps,gy_dps,gz_dps,acc_norm,gyro_norm,phase,pressure_pa,pressure_hpa,force_n
 *
 * Phase:
 *   0 = UNKNOWN
 *   1 = STATIONARY_OR_ZERO_VELOCITY
 *   2 = GROUND_CONTACT_WITH_ROTATION
 *   3 = SWING_OR_ON_AIR
 *
 * Notes:
 * - No velocity / distance calculation in this phase.
 * - No Kalman filter in this phase.
 * - Nano preprocesses raw IMU into features.
 * - UNO Q receives BLE payload and stores/displays data.
 * - Connect-first: the Nano reads the IMU and emits a payload (BLE notify +
 *   Serial echo together) only while a BLE central is connected. Before that it
 *   just advertises and prints a periodic "waiting" heartbeat.
 * --------------------------------------------------------------------------
 */

#include <Arduino_LSM9DS1.h>
#include <ArduinoBLE.h>
#include <Adafruit_BME680.h>
#include <Wire.h>

// BLE contract (DEVICE_NAME / SERVICE_UUID / CHAR_UUID / GRAVITY / SEND_INTERVAL_MS / phase
// thresholds) — single source of truth in protocol/ble_contract.json, generated by
// protocol/gen_contract.py. DO NOT hand-edit the header.
#include "ble_contract.h"

// --------------------------------------------------------------------------
// Constants
// --------------------------------------------------------------------------

// Init recovery: instead of hanging forever on a failed IMU/BLE init, retry a few times then
// reboot (NVIC_SystemReset) so a transient power-up fault can self-recover unattended.
const unsigned long INIT_RETRY_MS    = 1000;
const unsigned int  INIT_MAX_ATTEMPTS = 10;

const unsigned long BARO_INTERVAL_MS = 500;
const int           BARO_FILTER_SIZE = 5;
const float SENSOR_AREA_M2  = 0.000001f; // tip contact area in m² (1e-6 m² = 1 mm²) — adjust as needed

// --------------------------------------------------------------------------
// Phase codes
// --------------------------------------------------------------------------

enum Phase {
  PHASE_UNKNOWN                 = 0,
  PHASE_STATIONARY_OR_ZERO_VEL  = 1,
  PHASE_GROUND_CONTACT_ROTATION = 2,
  PHASE_SWING_OR_ON_AIR         = 3,
};

// --------------------------------------------------------------------------
// BLE objects
// --------------------------------------------------------------------------

BLEService imuService(SERVICE_UUID);

// Use 160 bytes to avoid payload truncation.
// CSV payload is easier for MVP, but binary packet is better later.
BLEStringCharacteristic imuChar(
  CHAR_UUID,
  BLERead | BLENotify,
  160
);

// --------------------------------------------------------------------------
// State
// --------------------------------------------------------------------------

unsigned long lastSendMs = 0;

// --------------------------------------------------------------------------
// Barometer (BME680)
// --------------------------------------------------------------------------

Adafruit_BME680 bme;
bool            baroOk           = false;
unsigned long   lastBaroMs       = 0;
float           baroBuffer[BARO_FILTER_SIZE];
int             baroIndex        = 0;
int             baroCount        = 0;
float           baroSum          = 0.0f;
float           cachedPressurePa = 0.0f;

void addBaroReading(float pa) {
  if (baroCount < BARO_FILTER_SIZE) {
    baroBuffer[baroIndex] = pa;
    baroSum += pa;
    baroCount++;
  } else {
    baroSum -= baroBuffer[baroIndex];
    baroBuffer[baroIndex] = pa;
    baroSum += pa;
  }
  baroIndex = (baroIndex + 1) % BARO_FILTER_SIZE;
}

float smoothedPressure() {
  if (baroCount == 0) return 0.0f;
  return baroSum / baroCount;
}

void initBaro() {
  Wire.begin();
  bool found = bme.begin(0x76);
  if (!found) found = bme.begin(0x77);
  if (found) {
    bme.setTemperatureOversampling(BME680_OS_2X);
    bme.setHumidityOversampling(BME680_OS_NONE);
    bme.setPressureOversampling(BME680_OS_16X);
    bme.setIIRFilterSize(BME680_FILTER_SIZE_3);
    bme.setGasHeater(0, 0);
    baroOk = true;
    Serial.println("BME680 init OK");
  } else {
    Serial.println("BME680 not found — pressure will be 0");
  }
}

void maybeReadBaro() {
  if (!baroOk) return;
  unsigned long now = millis();
  if (now - lastBaroMs < BARO_INTERVAL_MS) return;
  lastBaroMs = now;
  if (bme.performReading()) {
    addBaroReading(bme.pressure);
    cachedPressurePa = smoothedPressure();
  }
}

// --------------------------------------------------------------------------
// Small vector helper
// --------------------------------------------------------------------------

struct Vec3 {
  float x;
  float y;
  float z;
};

Vec3 vscale(Vec3 v, float s) {
  Vec3 out;
  out.x = v.x * s;
  out.y = v.y * s;
  out.z = v.z * s;
  return out;
}

float vmag(Vec3 v) {
  return sqrt(v.x * v.x + v.y * v.y + v.z * v.z);
}

// --------------------------------------------------------------------------
// IMU read
// --------------------------------------------------------------------------

bool readImu(Vec3& acc, Vec3& gyro) {
  if (!IMU.accelerationAvailable() || !IMU.gyroscopeAvailable()) {
    return false;
  }

  // Accelerometer unit from Arduino_LSM9DS1 = g
  IMU.readAcceleration(acc.x, acc.y, acc.z);

  // Gyroscope unit = deg/s
  IMU.readGyroscope(gyro.x, gyro.y, gyro.z);

  return true;
}

// --------------------------------------------------------------------------
// Lightweight phase classification
// --------------------------------------------------------------------------

int classifyPhase(float accNorm, float gyroNorm) {
  float accDelta = fabs(accNorm - GRAVITY);
  bool nearGravity = accDelta < ACC_NEAR_G_THRESHOLD;

  if (nearGravity && gyroNorm < GYRO_ZERO_THRESHOLD) {
    return PHASE_STATIONARY_OR_ZERO_VEL;
  }

  if (
    nearGravity &&
    gyroNorm >= GYRO_ZERO_THRESHOLD &&
    gyroNorm < GYRO_SWING_THRESHOLD
  ) {
    return PHASE_GROUND_CONTACT_ROTATION;
  }

  if (
    accDelta >= ACC_NEAR_G_THRESHOLD ||
    gyroNorm >= GYRO_SWING_THRESHOLD
  ) {
    return PHASE_SWING_OR_ON_AIR;
  }

  return PHASE_UNKNOWN;
}

// --------------------------------------------------------------------------
// BLE connection status
// --------------------------------------------------------------------------

// Poll BLE; log connect/disconnect transitions + a periodic "waiting" heartbeat;
// re-arm advertising after a disconnect. Returns the current connection state.
bool updateConnection() {
  static bool wasConnected = false;
  static unsigned long lastWaitingLogMs = 0;

  BLEDevice central = BLE.central();
  bool connected = central && central.connected();

  if (connected && !wasConnected) {
    Serial.print("central connected: ");
    Serial.println(central.address());
  } else if (!connected && wasConnected) {
    Serial.println("central disconnected; advertising again");
    BLE.advertise();                 // re-arm advertising (some ArduinoBLE versions stop after disconnect)
  } else if (!connected) {
    unsigned long now = millis();    // heartbeat so a bare Serial Monitor shows we're alive + waiting
    if (now - lastWaitingLogMs >= 2000) {
      lastWaitingLogMs = now;
      Serial.println("waiting for a BLE central (UNO Q) to connect...");
    }
  }

  wasConnected = connected;
  return connected;
}

// --------------------------------------------------------------------------
// Publish payload every 50 ms (called only while a central is connected)
// --------------------------------------------------------------------------

void maybePublish(
  Vec3 accMs2,
  Vec3 gyro,
  float accNorm,
  float gyroNorm,
  int phase,
  float pressurePa
) {
  unsigned long now = millis();

  if (now - lastSendMs < SEND_INTERVAL_MS) {
    return;
  }

  lastSendMs = now;

  char payload[160];

  snprintf(
    payload,
    sizeof(payload),
    "IMU,%lu,%.4f,%.4f,%.4f,%.4f,%.4f,%.4f,%.4f,%.4f,%d,%.2f,%.2f,%.4f",
    now,
    accMs2.x,
    accMs2.y,
    accMs2.z,
    gyro.x,
    gyro.y,
    gyro.z,
    accNorm,
    gyroNorm,
    phase,
    pressurePa,
    pressurePa / 100.0f,
    pressurePa * SENSOR_AREA_M2   // Pa * m² = N
  );

  imuChar.writeValue(payload);   // BLE notify to the connected central
  Serial.println(payload);       // mirror to Serial for debug
}

// --------------------------------------------------------------------------
// Setup
// --------------------------------------------------------------------------

void setup() {
  Serial.begin(115200);

  // Bounded wait so the device can still run without Serial Monitor.
  unsigned long t0 = millis();
  while (!Serial && millis() - t0 < 3000) {
    delay(10);
  }

  if (!IMU.begin()) {
    Serial.println("IMU init FAILED");
    Serial.println("Check:");
    Serial.println("- Board is Nano 33 BLE original generation");
    Serial.println("- Library is Arduino_LSM9DS1");
    Serial.println("- Tools > Board is Arduino Nano 33 BLE");
    // Retry instead of hanging; reboot if it stays dead so a transient fault can recover.
    for (unsigned int attempt = 1; !IMU.begin(); attempt++) {
      if (attempt >= INIT_MAX_ATTEMPTS) {
        Serial.println("IMU still failing — rebooting");
        delay(100);
        NVIC_SystemReset();
      }
      delay(INIT_RETRY_MS);
    }
  }

  Serial.println("IMU init OK");

  if (!BLE.begin()) {
    Serial.println("BLE init FAILED");
    for (unsigned int attempt = 1; !BLE.begin(); attempt++) {
      if (attempt >= INIT_MAX_ATTEMPTS) {
        Serial.println("BLE still failing — rebooting");
        delay(100);
        NVIC_SystemReset();
      }
      delay(INIT_RETRY_MS);
    }
  }

  Serial.println("BLE init OK");

  initBaro();

  BLE.setLocalName(DEVICE_NAME);
  BLE.setDeviceName(DEVICE_NAME);
  BLE.setAdvertisedService(imuService);

  imuService.addCharacteristic(imuChar);
  BLE.addService(imuService);

  // Initial value
  imuChar.writeValue("IMU,0,0,0,0,0,0,0,0,0,0,0,0,0");

  BLE.advertise();

  Serial.print("BLE advertising started as \"");
  Serial.print(DEVICE_NAME);
  Serial.println("\"");

  Serial.println(
    "IMU,timestamp_ms,ax_ms2,ay_ms2,az_ms2,gx_dps,gy_dps,gz_dps,acc_norm,gyro_norm,phase,pressure_pa,pressure_hpa,force_n"
  );

  lastSendMs = millis();
}

// --------------------------------------------------------------------------
// Main loop
// --------------------------------------------------------------------------

void loop() {
  maybeReadBaro();   // samples every 500 ms regardless of BLE state

  bool connected = updateConnection();

  // Connect-first: don't read the IMU or emit anything until a central is connected.
  if (!connected) {
    return;
  }

  Vec3 acc;
  Vec3 gyro;
  if (!readImu(acc, gyro)) {
    return;   // run as fast as IMU data is available
  }

  Vec3 accMs2 = vscale(acc, GRAVITY);     // g -> m/s^2 (gyro stays deg/s)

  float accNorm = vmag(accMs2);
  float gyroNorm = vmag(gyro);

  int phase = classifyPhase(accNorm, gyroNorm);

  // One payload at most every 50 ms: BLE notify + Serial echo together.
  maybePublish(
    accMs2,
    gyro,
    accNorm,
    gyroNorm,
    phase,
    cachedPressurePa
  );
}
